app/models.py
from app import db

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    created_at = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp())
    scores = db.relationship('Score', backref='user', lazy=True)

class Quiz(db.Model):
    __tablename__ = 'quizzes'
    id = db.Column(db.Integer, primary_key=True)
    quiz_id = db.Column(db.String(255), unique=True, nullable=False)
    quiz_name = db.Column(db.String(255), nullable=False)
    questions = db.relationship('Question', backref='quizzes', lazy=True)
    scores = db.relationship('Score', backref='quiz', lazy=True)

class Question(db.Model):
    __tablename__ = 'questions'
    id = db.Column(db.Integer, primary_key=True)
    quiz_id = db.Column(db.Integer, db.ForeignKey('quizzes.id'), nullable=False)
    question_text = db.Column(db.Text, nullable=False)
    options = db.relationship('QuestionOption', backref='questions', lazy=True)

class QuestionOption(db.Model):
    __tablename__ = 'questionoptions'
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'), nullable=False)
    optanswer = db.Column(db.Text, nullable=False)
    correct_answer = db.Column(db.Boolean, default=False)

class Score(db.Model):
    __tablename__ = 'scores'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    quiz_id = db.Column(db.Integer, db.ForeignKey('quizzes.id'), nullable=False)
    score = db.Column(db.Integer, default=0)
    
    def to_dict(self):
        return {
            'id': self.id,
            'quiz_id': self.quiz_id,
            'user_id': self.user_id,
            'score': self.score
        }
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_socketio import SocketIO

db = SQLAlchemy()
migrate = Migrate()
socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config.Config')

    db.init_app(app)
    migrate.init_app(app, db)
    socketio.init_app(app)

    from app.routes import main_bp
    app.register_blueprint(main_bp)

    from app.sockets import setup_socketio
    setup_socketio(app)

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session ,jsonify,make_response
from app import db
from app.models import User,Score
from app.quizhelper import *
import uuid

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html')

@main_bp.route('/quizlist', methods=['GET', 'POST'])
def quizlist():
    user = None
    if request.method == 'POST':
        username = request.form.get('username')
        if username:
            user = User.query.filter_by(username=username).first()
            if not user:
                user = User(username=username)
                db.session.add(user)
                db.session.commit()
            session['user_id'] = user.id
        else:
            return redirect(url_for('main.index'))
    
    user_id = session.get('user_id')
    if user_id:
        user = User.query.get(user_id) 
        quizzes = get_quizzes()
        return render_template('list_quizzes.html', quizzes=quizzes, loginuser = user)
    else:
        return redirect(url_for('main.index'))
     
@main_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('main.index'))

#Get question list by quiz_id
@main_bp.route('/questions/<int:user_id>/<int:quiz_id>', methods=['GET'])
def questions(user_id:str,quiz_id: str):
    questions_list = get_questions(quiz_id)
    if user_id:
        user = User.query.get(user_id)
        user_scores = [score for score in user.scores if score.quiz_id == quiz_id]
        first_score = user_scores[0] if user_scores else {'quiz_id':quiz_id,'score':0}
        return render_template('question.html', questions=questions_list,loginuser = user,user_score=first_score)
    return redirect(url_for('main.index'))

#Submit answer
@main_bp.route('/submit_answer', methods=['POST'])
def submit_answer():
    if request.method == 'POST':
        try:    
            data = request.json  
            selected_choices = data.get('selectedChoices', [])
            quiz_id = data.get('quiz_ID')
            user_id = data.get('user_id')
            points = 0
            for anwser in selected_choices:
                points += check_answer(anwser['questionid'],anwser['answervalue'])
            #Insert point to db
            user_score = add_user_score(int(quiz_id),user_id,points)
            #emit score here
            return jsonify({'success': True, 'user_score': user_score.to_dict()}), 200
        except Exception as e:
            return jsonify({'success': False, 'error': str(e)}), 500

@main_bp.route('/scores')
def scores():
    all_scores = Score.query.all()
    return render_template('score.html', scores=all_scores)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <script src="https://cdn.socket.io/4.5.4/socket.io.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="/static/style.css">
    <script type="text/javascript" src="/static/scriptHelper.js"></script>
</head>
<body>
    <h1>Quiz Application</h1>
    {% block content %}{% endblock %}
    {% if loginuser %}
        <input id="username" type="hidden" value="{{ loginuser['username'] }}" />
        <input id="userid" type="hidden" value="{{ loginuser['id'] }}" />
    {% endif %}
    {% if user_score %}
        <input id="room" type="hidden" value="{{ user_score['quiz_id'] }}"/>
        <input id="user_score" type="hidden" value="{{ user_score['score'] }}"/>
    {% endif %}
    <div id="user-list"></div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Quiz App{% endblock %}

{% block content %}
    <div class="form-container">
        <h1>Welcome to the Vocabulary Quiz App</h1>
        <form action="{{ url_for('main.quizlist') }}" method="POST">
            <label for="username">Enter your username:</label>
            <input type="text" id="username" name="username" required>
            <button type="submit" id="join-button">Join Quiz</button>
        </form>
    </div>
{% endblock %}

app/templates/list_quizzes.html
{% extends "base.html" %}
{% block title %}Quizzes App{% endblock %}

{% block content %}
    <div class="user_section">
        {% if loginuser %}
        <p>Welcome, {{ loginuser.username }}!|<a href="{{ url_for('main.logout') }}">Logout</a></p>
        {% else %}
            <a href="{{ url_for('main.index') }}">Login</a>
        {% endif %}
    </div>
    <ul>
        {% for quiz in quizzes %}
            <li>
                <a href="/questions/{{ loginuser.id }}/{{ quiz['id'] }}">{{ quiz['quiz_name'] }}</a>
            </li>
        {% else %}
            <li>No quizzes available</li>
        {% endfor %}
    </ul>
    <!-- <div class="nav-links">
        <a href="/login">Login</a> | <a href="/register">Register</a>
    </div> -->
{% endblock %}

app/templates/question.html
{% extends "base.html" %}
{% block title %}Question list{% endblock %}

{% block content %}
<div class="user_section">
    {% if loginuser %}
        <p>Welcome, {{ loginuser.username }}!|<a id="logout" href="{{ url_for('main.logout') }}">Logout</a></p>
    {% else %}
        <a href="{{ url_for('main.index') }}">Login</a>
    {% endif %}
</div>
    <a href="{{ url_for('main.quizlist') }}">Back to quizzes list</a>
    {% set letters = ['A', 'B', 'C', 'D','E','F'] %}
    <form id="quiz-form" action="{{ url_for('main.submit_answer') }}" method="POST">
        <input id="quizID" type="hidden" value="{{ user_score['quiz_id'] }}"/>
        <ul>
            {% for question in questions %}
                <ul class="question-group" data-question="{{question['question_id']}}">
                    Question {{ loop.index }}: {{ question['question_text'] }}
                    {% set choiceID = loop.index %}
                        {% for optquestion in question['options'] %}
                            <li>
                                <label>
                                    <input type="radio" name="choice{{choiceID}}" value="{{ optquestion['optanswer']}}">
                                    {{ letters[loop.index0] }}.{{ optquestion['optanswer']}}
                                </label>
                                
                            </li>
                        {% endfor %}
                    <div class="error-message error"></div>
                </ul> 
            
            {% else %}
                <li>No questions available</li>
            {% endfor %}
        </ul>
        {% if questions|length > 0 %}
        <button id="submit-answer">Submit</button>
        {% endif %}
    </form>

    <div id="score-section">
        <h2>Your Score: <span id="user-score"></span></h2>
    </div>

    <div id="leaderboard-section">
        <h2>Leaderboard</h2>
        <ul id="leaderboard"></ul>
    </div>

{% endblock %}